cmake_minimum_required(VERSION 3.25)
foreach(required IN ITEMS TEST_SOURCE_DIR TEST_BINARY_DIR TEST_CASE TEST_GENERATOR TEST_C_COMPILER)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
set(probe "${TEST_BINARY_DIR}/${TEST_CASE}")
file(MAKE_DIRECTORY "${probe}/package")
set(version "2.11.3")
if(TEST_CASE STREQUAL "wrong-version")
    set(version "2.10.0")
endif()
set(package_target "add_library(utf8proc::utf8proc INTERFACE IMPORTED)")
if(TEST_CASE STREQUAL "missing-target")
    set(package_target "")
endif()
file(WRITE "${probe}/package/utf8proc-config.cmake" "${package_target}\n")
file(WRITE "${probe}/package/utf8proc-config-version.cmake"
    "set(PACKAGE_VERSION ${version})\nif(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)\nset(PACKAGE_VERSION_EXACT TRUE)\nset(PACKAGE_VERSION_COMPATIBLE TRUE)\nendif()\n")
set(setup "set(RYNUI_DEPENDENCY_MODE SYSTEM)\nset(utf8proc_DIR \"${probe}/package\")")
set(expected "")
if(TEST_CASE STREQUAL "missing-package")
    string(APPEND setup "\nset(CMAKE_DISABLE_FIND_PACKAGE_utf8proc TRUE)")
    set(expected "REQUIRED package cannot[ \r\n]+be disabled")
elseif(TEST_CASE STREQUAL "wrong-version")
    set(expected "Could not find a configuration file")
elseif(TEST_CASE STREQUAL "missing-target")
    set(expected "missing required target")
elseif(TEST_CASE STREQUAL "invalid-mode")
    string(APPEND setup "\nset(RYNUI_DEPENDENCY_MODE AUTO)")
    set(expected "requires explicit BUNDLED or SYSTEM")
elseif(TEST_CASE STREQUAL "bundled-offline" OR TEST_CASE STREQUAL "bundled-wrong-version")
    set(source "${TEST_UTF8PROC_SOURCE}")
    if(TEST_CASE STREQUAL "bundled-wrong-version")
        set(source "${probe}/wrong-source")
        file(MAKE_DIRECTORY "${source}")
        file(WRITE "${source}/utf8proc.h" "#define UTF8PROC_VERSION_MAJOR 1\n")
        set(expected "header version mismatch")
    endif()
    set(setup "set(RYNUI_DEPENDENCY_MODE BUNDLED)\nset(FETCHCONTENT_FULLY_DISCONNECTED ON)\nset(FETCHCONTENT_SOURCE_DIR_RYNUI_UTF8PROC \"${source}\")")
endif()
file(WRITE "${probe}/CMakeLists.txt"
    "cmake_minimum_required(VERSION 3.25)\nproject(Utf8procProbe LANGUAGES C)\n${setup}\ninclude(\"${TEST_SOURCE_DIR}/cmake/dependencies/RynUIUtf8proc.cmake\")\nrynui_resolve_utf8proc()\nrynui_resolve_utf8proc()\nif(NOT TARGET RynUI::Utf8proc)\nmessage(FATAL_ERROR \"Missing normalized target\")\nendif()\nif(RYNUI_DEPENDENCY_MODE STREQUAL \"BUNDLED\")\nget_target_property(kind utf8proc TYPE)\nif(NOT kind STREQUAL \"STATIC_LIBRARY\" OR UTF8PROC_INSTALL OR UTF8PROC_ENABLE_TESTING OR LIB_FUZZING_ENGINE)\nmessage(FATAL_ERROR \"Bundled options were not isolated\")\nendif()\nendif()\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${probe}" -B "${probe}/build"
    -G "${TEST_GENERATOR}" "-DCMAKE_C_COMPILER=${TEST_C_COMPILER}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(expected STREQUAL "")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Expected success: ${output}\n${error}")
    endif()
else()
    if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${expected}")
        message(FATAL_ERROR "Expected '${expected}': ${output}\n${error}")
    endif()
endif()
