include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/RynUIDependencyLock.cmake")

function(rynui_resolve_utf8proc)
    if(NOT RYNUI_DEPENDENCY_MODE MATCHES "^(BUNDLED|SYSTEM)$")
        message(FATAL_ERROR "utf8proc requires explicit BUNDLED or SYSTEM dependency mode.")
    endif()
    if(TARGET RynUI::Utf8proc)
        return()
    endif()
    if(RYNUI_DEPENDENCY_MODE STREQUAL "BUNDLED")
        include(FetchContent)
        set(BUILD_SHARED_LIBS OFF)
        set(UTF8PROC_INSTALL OFF CACHE BOOL "Disable utf8proc install" FORCE)
        set(UTF8PROC_ENABLE_TESTING OFF CACHE BOOL "Disable upstream network tests" FORCE)
        set(LIB_FUZZING_ENGINE OFF CACHE BOOL "Disable utf8proc fuzzing" FORCE)
        FetchContent_Declare(rynui_utf8proc
            URL "${RYNUI_UTF8PROC_SOURCE_URL}"
            URL_HASH "SHA256=${RYNUI_UTF8PROC_SOURCE_SHA256}"
            DOWNLOAD_EXTRACT_TIMESTAMP FALSE
            SOURCE_SUBDIR __rynui_validate_before_configure)
        FetchContent_MakeAvailable(rynui_utf8proc)
        # Source overrides bypass archive verification; still reject wrong API identity.
        file(READ "${rynui_utf8proc_SOURCE_DIR}/utf8proc.h" utf8proc_header)
        foreach(part IN ITEMS MAJOR MINOR PATCH)
            if(part STREQUAL "MAJOR")
                set(expected 2)
            elseif(part STREQUAL "MINOR")
                set(expected 11)
            else()
                set(expected 3)
            endif()
            if(NOT utf8proc_header MATCHES "#define UTF8PROC_VERSION_${part} +${expected}([\r\n]|$)")
                message(FATAL_ERROR "Bundled utf8proc header version mismatch: ${part}")
            endif()
        endforeach()
        add_subdirectory("${rynui_utf8proc_SOURCE_DIR}" "${rynui_utf8proc_BINARY_DIR}")
        set(upstream_target utf8proc)
    else()
        find_package(utf8proc ${RYNUI_UTF8PROC_VERSION} EXACT CONFIG REQUIRED)
        set(upstream_target utf8proc::utf8proc)
    endif()
    if(NOT TARGET ${upstream_target})
        message(FATAL_ERROR "utf8proc package missing required target ${upstream_target}")
    endif()
    add_library(rynui_utf8proc_dependency INTERFACE)
    add_library(RynUI::Utf8proc ALIAS rynui_utf8proc_dependency)
    target_link_libraries(rynui_utf8proc_dependency INTERFACE ${upstream_target})
endfunction()
