include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/RynUIDependencyLock.cmake")

function(rynui_resolve_sheenbidi)
    if(NOT RYNUI_DEPENDENCY_MODE MATCHES "^(BUNDLED|SYSTEM)$")
        message(FATAL_ERROR "SheenBidi requires explicit BUNDLED or SYSTEM dependency mode.")
    endif()
    if(TARGET RynUI::SheenBidi)
        return()
    endif()
    if(RYNUI_DEPENDENCY_MODE STREQUAL "BUNDLED")
        include(FetchContent)
        set(BUILD_SHARED_LIBS OFF)
        set(SB_CONFIG_UNITY ON CACHE BOOL "Build locked SheenBidi unity source" FORCE)
        set(SB_CONFIG_EXPERIMENTAL_TEXT_API OFF CACHE BOOL "Use stable UBA API only" FORCE)
        set(BUILD_GENERATOR OFF CACHE BOOL "Do not build SheenBidi Unicode generator" FORCE)
        FetchContent_Declare(rynui_sheenbidi
            URL "${RYNUI_SHEENBIDI_SOURCE_URL}"
            URL_HASH "SHA256=${RYNUI_SHEENBIDI_SOURCE_SHA256}"
            DOWNLOAD_EXTRACT_TIMESTAMP FALSE
            SOURCE_SUBDIR __rynui_validate_before_configure)
        FetchContent_MakeAvailable(rynui_sheenbidi)
        file(READ "${rynui_sheenbidi_SOURCE_DIR}/Headers/SheenBidi/SBVersion.h" version_header)
        if(NOT version_header MATCHES "SHEENBIDI_VERSION_STRING[ \t]+\"3[.]0[.]0\"")
            message(FATAL_ERROR "Bundled SheenBidi header version mismatch")
        endif()
        add_subdirectory("${rynui_sheenbidi_SOURCE_DIR}" "${rynui_sheenbidi_BINARY_DIR}")
        # The upstream MSVC atomic fallback includes windows.h. Enforce standard
        # C17 atomics so portable Core never selects that OS SDK branch.
        target_compile_features(SheenBidi PRIVATE c_std_17)
        if(MSVC)
            include(CheckCSourceCompiles)
            set(CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS} /std:c17 /experimental:c11atomics")
            check_c_source_compiles("#include <stdatomic.h>
                #ifdef __STDC_NO_ATOMICS__
                #error Standard atomics are required
                #endif
                int main(void) { atomic_flag f = ATOMIC_FLAG_INIT;
                    atomic_flag_clear(&f); atomic_thread_fence(memory_order_seq_cst);
                    return atomic_flag_test_and_set(&f); }" RYNUI_MSVC_C17_ATOMICS)
            if(NOT RYNUI_MSVC_C17_ATOMICS)
                message(FATAL_ERROR "Portable SheenBidi requires MSVC standard C17 atomics")
            endif()
            target_compile_options(SheenBidi PRIVATE /experimental:c11atomics)
        endif()
        set(upstream_target SheenBidi)
        foreach(name IN ITEMS BIDI_TEST BIDI_CHARACTER_TEST)
            if(name STREQUAL "BIDI_TEST")
                set(filename BidiTest.txt)
            else()
                set(filename BidiCharacterTest.txt)
            endif()
            set(test_file "${rynui_sheenbidi_SOURCE_DIR}/Tools/Unicode/${filename}")
            file(SHA256 "${test_file}" actual_hash)
            if(NOT actual_hash STREQUAL RYNUI_${name}_SOURCE_SHA256)
                message(FATAL_ERROR "SheenBidi Unicode 17 fixture hash mismatch: ${filename}")
            endif()
            set(RYNUI_${name}_FILE "${test_file}" PARENT_SCOPE)
        endforeach()
    else()
        find_package(SheenBidi ${RYNUI_SHEENBIDI_VERSION} EXACT CONFIG REQUIRED)
        set(upstream_target SheenBidi::SheenBidi)
        if(BUILD_TESTING)
            foreach(name IN ITEMS BIDI_TEST BIDI_CHARACTER_TEST)
                set(RYNUI_${name}_FILE "" CACHE FILEPATH "Explicit Unicode 17 ${name} fixture")
                if(NOT EXISTS "${RYNUI_${name}_FILE}" OR IS_DIRECTORY "${RYNUI_${name}_FILE}")
                    message(FATAL_ERROR "SYSTEM tests require explicit RYNUI_${name}_FILE")
                endif()
                file(SHA256 "${RYNUI_${name}_FILE}" actual_hash)
                if(NOT actual_hash STREQUAL RYNUI_${name}_SOURCE_SHA256)
                    message(FATAL_ERROR "SYSTEM Unicode 17 ${name} fixture hash mismatch")
                endif()
            endforeach()
        endif()
    endif()
    if(NOT TARGET ${upstream_target})
        message(FATAL_ERROR "SheenBidi package missing required target ${upstream_target}")
    endif()
    add_library(rynui_sheenbidi_dependency INTERFACE)
    add_library(RynUI::SheenBidi ALIAS rynui_sheenbidi_dependency)
    target_link_libraries(rynui_sheenbidi_dependency INTERFACE ${upstream_target})
endfunction()
