"""Build the private, deterministic CFF outline container from locked Ant SVGs.

Maintenance only: python -m pip install --target out/icon-tools fonttools==4.60.1
Run with PYTHONPATH=out/icon-tools. Normal builds use the checked-in byte array.
"""

import argparse
import hashlib
import io
import json
from pathlib import Path
import xml.etree.ElementTree as ET

import fontTools
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.t2CharStringPen import T2CharStringPen
from fontTools.svgLib.path import SVGPath

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "third_party/ant-design-icons"
OUTPUT = ROOT / "src/icons/ant_design_icon_font.inc"
MANIFEST = ASSETS / "manifest.json"
ICONS = [
    ("EyeOutlined", "outlined-eye.svg"),
    ("EyeInvisibleOutlined", "outlined-eye-invisible.svg"),
    ("SearchOutlined", "outlined-search.svg"),
    ("CloseCircleFilled", "filled-close-circle.svg"),
    ("MenuOutlined", "outlined-menu.svg"),
    ("SunOutlined", "outlined-sun.svg"),
    ("MoonOutlined", "outlined-moon.svg"),
    ("UserOutlined", "outlined-user.svg"),
    ("LockOutlined", "outlined-lock.svg"),
    ("CopyOutlined", "outlined-copy.svg"),
    ("CheckOutlined", "outlined-check.svg"),
    ("EditOutlined", "outlined-edit.svg"),
    ("DownOutlined", "outlined-down.svg"),
    ("UpOutlined", "outlined-up.svg"),
]

# RynUI-owned primitives; separate codepoints keep the locked Ant indices stable.
PRIMITIVES = [
    ("TooltipArrowDown", 0xF000, [(0, 0), (1024, 0), (512, 512)]),
    ("TooltipArrowUp", 0xF001, [(0, 512), (512, 0), (1024, 512)]),
    ("TooltipArrowRight", 0xF002, [(0, 0), (512, 512), (0, 1024)]),
    ("TooltipArrowLeft", 0xF003, [(512, 0), (512, 1024), (0, 512)]),
]


def generate():
    if fontTools.version != "4.60.1":
        raise RuntimeError("Regeneration requires fonttools==4.60.1")
    names = [".notdef"] + [name for name, _ in ICONS] + [name for name, _, _ in PRIMITIVES]
    chars = {".notdef": T2CharStringPen(1024, None).getCharString()}
    entries = []
    for index, (name, filename) in enumerate(ICONS):
        source = (ASSETS / filename).read_bytes()
        root = ET.fromstring(source)
        x, y, width, height = map(float, root.attrib["viewBox"].split())
        if width != height or width <= 0:
            raise ValueError("Icon viewBox must be a nonempty square")
        scale = 1024 / width
        pen = T2CharStringPen(1024, None, roundTolerance=0.01)
        SVGPath.fromstring(source, transform=(scale, 0, 0, -scale,
                                              -x * scale, 896 + y * scale)).draw(pen)
        chars[name] = pen.getCharString()
        entries.append({"name": name, "file": filename,
                        "codepoint": 0xE000 + index,
                        "sha256": hashlib.sha256(source).hexdigest()})
    primitives = []
    for name, codepoint, points in PRIMITIVES:
        pen = T2CharStringPen(1024, None, roundTolerance=0.01)
        pen.moveTo((points[0][0], 896 - points[0][1]))
        for x, y in points[1:]:
            pen.lineTo((x, 896 - y))
        pen.closePath()
        chars[name] = pen.getCharString()
        primitives.append({"name": name, "codepoint": codepoint, "points": points,
                           "origin": "RynUI", "bounds": [min(x for x, y in points),
                               896 - max(y for x, y in points), max(x for x, y in points),
                               896 - min(y for x, y in points)]})
    builder = FontBuilder(1024, isTTF=False)
    builder.setupGlyphOrder(names)
    builder.setupCharacterMap({item["codepoint"]: item["name"] for item in entries + primitives})
    builder.setupCFF("RynUIAntIcons", {"FullName": "RynUI Ant Icons",
                     "FamilyName": "RynUI Ant Icons", "Weight": "Regular"}, chars, {})
    for name, _ in ICONS:
        if chars[name].calcBounds(None) is None:
            raise ValueError(f"Empty outline: {name}")
    for item in primitives:
        if list(chars[item["name"]].calcBounds(None)) != item["bounds"]:
            raise ValueError(f"Primitive bounds changed: {item['name']}")
    builder.setupHorizontalMetrics({name: (1024, 0) for name in names})
    builder.setupHorizontalHeader(ascent=896, descent=-128, lineGap=0)
    builder.setupNameTable({"familyName": "RynUI Ant Icons", "styleName": "Regular",
                           "uniqueFontIdentifier": "RynUIAntIcons-4.6.0-1",
                           "fullName": "RynUI Ant Icons", "psName": "RynUIAntIcons",
                           "version": "Version 1.0"})
    builder.setupOS2(sTypoAscender=896, sTypoDescender=-128, sTypoLineGap=0,
                    usWinAscent=896, usWinDescent=128, fsType=0)
    builder.setupPost()
    builder.font.recalcTimestamp = False
    builder.font["head"].created = builder.font["head"].modified = 3800000000
    data = io.BytesIO()
    builder.save(data)
    raw = data.getvalue()
    lines = ["// Generated by tools/generate_icon_assets.py; do not edit.",
             "// Ant Design icons-svg 4.6.0, MIT; see third_party/ant-design-icons/LICENSE.",
             "static constexpr unsigned char ant_design_icon_font_bytes[] = {"]
    lines += ["    " + ", ".join(f"0x{value:02x}" for value in raw[i:i + 16]) + ","
              for i in range(0, len(raw), 16)]
    lines += ["};", ""]
    manifest = {"package": "@ant-design/icons-svg", "version": "4.6.0",
                "upstream_commit": "7f2516ac91226d2b41f93b35cb5197c8d94f7189",
                "license_sha256": hashlib.sha256((ASSETS / "LICENSE").read_bytes()).hexdigest(),
                "fonttools_version": fontTools.version,
                "outline_container_sha256": hashlib.sha256(raw).hexdigest(), "icons": entries,
                "primitives": primitives}
    return "\n".join(lines), json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    source, manifest = generate()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != source or MANIFEST.read_text(encoding="utf-8") != manifest:
            raise SystemExit("Generated icon assets are out of date")
        print("Icon assets reproduce exactly")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(source, encoding="utf-8", newline="\n")
        MANIFEST.write_text(manifest, encoding="utf-8", newline="\n")
        print(f"Generated {len(ICONS)} icons")


if __name__ == "__main__":
    main()
